config:
  aws:region: ap-southeast-1
  k3s-cluster:vpc_cidr: "10.0.0.0/16"
  k3s-cluster:master_instance_type: t3.medium
  k3s-cluster:worker_instance_type: t2.small
  k3s-cluster:worker_count: "2"
  k3s-cluster:ssh_key_name: k3s-key
